In [2]:
import pandas as pd 
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression

In [3]:
train = pd.read_csv('data/lunchbox/train.csv')
test = pd.read_csv('data/lunchbox/test.csv')
sample = pd.read_csv('data/lunchbox/sample.csv', header=None)

In [4]:
train.head()

datetime    y week  soldout        name  kcal remarks event  payday  \
0  2013-11-18   90    月        0    厚切りイカフライ   NaN     NaN   NaN     NaN   
1  2013-11-19  101    火        1     手作りヒレカツ   NaN     NaN   NaN     NaN   
2  2013-11-20  118    水        0  白身魚唐揚げ野菜あん   NaN     NaN   NaN     NaN   
3  2013-11-21  120    木        1      若鶏ピリ辛焼   NaN     NaN   NaN     NaN   
4  2013-11-22  130    金        1    ビッグメンチカツ   NaN     NaN   NaN     NaN   

  weather precipitation  temperature  
0      快晴            --         19.8  
1      快晴            --         17.0  
2      快晴            --         15.5  
3      快晴            --         15.2  
4      快晴            --         16.1

In [5]:
trainX = train['temperature']
y = train['y']

In [6]:
testX = test["temperature"]

In [7]:
trainX = trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

In [8]:
model1 = LinearRegression()

In [9]:
model1.fit(trainX, y)

LinearRegression()

In [10]:
model1.coef_

array([-2.5023821])

In [11]:
model1.intercept_

134.79948383749922

In [12]:
pred = model1.predict(testX)

In [13]:
pred

array([ 84.25136537,  74.99255159,  62.9811175 ,  80.99826864,
        79.49683938,  76.49398085,  78.49588653,  69.48731097,
        67.73564349,  95.76232304,  88.25517673,  77.24469548,
        74.99255159,  84.25136537,  96.01256125,  98.01446693,
        88.00493852,  77.99541011,  87.00398568,  85.75279463,
        85.75279463,  87.75470031,  87.5044621 ,  94.7613702 ,
        86.75374747,  84.50160358,  81.74898327,  98.01446693,
        98.76518156,  86.00303284,  95.26184662,  99.01541977,
        94.51113199,  97.51399051, 108.52447176,  97.51399051,
       106.27232787, 111.7775685 ,  97.01351409,  96.51303767])

In [14]:
sample.head()

0   1
0  2014-10-1  24
1  2014-10-2  71
2  2014-10-3  25
3  2014-10-6  32
4  2014-10-7  60

In [15]:
sample[1] = pred

In [16]:
sample.head()

0          1
0  2014-10-1  84.251365
1  2014-10-2  74.992552
2  2014-10-3  62.981117
3  2014-10-6  80.998269
4  2014-10-7  79.496839

In [17]:
sample.to_csv('data/lunchbox/submit1.csv', index=None, header=None)

In [18]:
train.isnull().sum()

datetime           0
y                  0
week               0
soldout            0
name               0
kcal              41
remarks          186
event            193
payday           197
weather            0
precipitation      0
temperature        0
dtype: int64

In [19]:
train.head()

datetime    y week  soldout        name  kcal remarks event  payday  \
0  2013-11-18   90    月        0    厚切りイカフライ   NaN     NaN   NaN     NaN   
1  2013-11-19  101    火        1     手作りヒレカツ   NaN     NaN   NaN     NaN   
2  2013-11-20  118    水        0  白身魚唐揚げ野菜あん   NaN     NaN   NaN     NaN   
3  2013-11-21  120    木        1      若鶏ピリ辛焼   NaN     NaN   NaN     NaN   
4  2013-11-22  130    金        1    ビッグメンチカツ   NaN     NaN   NaN     NaN   

  weather precipitation  temperature  
0      快晴            --         19.8  
1      快晴            --         17.0  
2      快晴            --         15.5  
3      快晴            --         15.2  
4      快晴            --         16.1

In [21]:
avg = train['kcal'].mean()
avg

404.4096385542169

In [22]:
trainX = train['kcal'].fillna(avg)
testX = test['kcal'].fillna(avg)

In [23]:
trainX

0      404.409639
1      404.409639
2      404.409639
3      404.409639
4      404.409639
          ...    
202    408.000000
203    394.000000
204    404.409639
205    404.000000
206    398.000000
Name: kcal, Length: 207, dtype: float64

In [24]:
trainX = trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

In [25]:
y = train['y']

In [26]:
model2 = LinearRegression()

In [27]:
model2.fit(trainX, y)

LinearRegression()

In [28]:
model2.coef_

array([0.13195178])

In [29]:
model2.intercept_

33.26061577029441

In [30]:
pred2 = model2.predict(testX)

In [33]:
sample[1] = pred2
sample.head()

0          1
0  2014-10-1  88.680364
1  2014-10-2  88.020605
2  2014-10-3  86.701088
3  2014-10-6  86.041329
4  2014-10-7  89.999882

In [34]:
sample.to_csv('data/lunchbox/submit2.csv', index=None, header=None)